#---------------------------------#
#         version format          #
#---------------------------------#
version: 1.0.{build}


#---------------------------------#
#    environment configuration    #
#---------------------------------#
os: Windows Server 2012 R2


#---------------------------------#
#              build              #
#---------------------------------#
pull_requests:
  do_not_increment_build_number: true

skip_tags: true

build:
  verbosity: minimal


#---------------------------------#
#       build configuration       #
#---------------------------------#
build_script:
  - cmd: nuget pack src\csproj-ignition.nuspec -Version %appveyor_build_version%


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
- path: '*.nupkg'
  name: NuGet


#---------------------------------#
#              nuget              #
#---------------------------------#
nuget:
  project_feed: true


#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:
  # Email
  - provider: Email
    to:
      - mattias.kindborg@email.com
    on_build_status_changed: true